import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import type { ChartConfig } from "@/lib/chart-types";
import type { ParsedData } from "@/lib/data-processing";

export interface ReportPayload {
  title: string;
  fileName: string;
  data: ParsedData | null;
  charts: ChartConfig[];
  executiveSummary?: string;
  insights?: string[];
  recommendations?: string[];
  predictions?: string[];
}

const NAVY: [number, number, number] = [30, 39, 97];
const INK: [number, number, number] = [33, 41, 60];
const MUTED: [number, number, number] = [110, 119, 138];
const ACCENT: [number, number, number] = [79, 70, 229];

function fmtNum(n: number): string {
  if (!isFinite(n)) return "—";
  if (Math.abs(n) >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (Math.abs(n) >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toFixed(2).replace(/\.00$/, "");
}

function computeKPIs(data: ParsedData) {
  const numericCols = data.columns.filter((c) => c.type === "number").map((c) => c.name);
  const stringCols = data.columns.filter((c) => c.type === "string").map((c) => c.name);
  const find = (cols: string[], keys: string[]) =>
    cols.find((n) => keys.some((k) => n.toLowerCase().includes(k))) ?? null;

  const revCol = find(numericCols, ["revenue", "sales", "amount", "total", "income"]) ?? numericCols[0];
  const profCol = find(numericCols, ["profit", "margin", "net"]);
  const regionCol = find(stringCols, ["region", "country", "state", "city"]);
  const productCol = find(stringCols, ["product", "item", "sku", "name", "category"]);

  const sum = (col: string | null | undefined) =>
    col ? data.rows.reduce((s, r) => s + (Number(r[col]) || 0), 0) : 0;

  const totalRevenue = sum(revCol);
  const totalProfit = profCol ? sum(profCol) : 0;
  const growthPct = (() => {
    if (!revCol) return null;
    const n = data.rows.length;
    if (n < 4) return null;
    const half = Math.floor(n / 2);
    const first = data.rows.slice(0, half).reduce((s, r) => s + (Number(r[revCol]) || 0), 0);
    const second = data.rows.slice(half).reduce((s, r) => s + (Number(r[revCol]) || 0), 0);
    if (first === 0) return null;
    return ((second - first) / first) * 100;
  })();

  const bestBy = (catCol: string | null) => {
    if (!catCol || !revCol) return null;
    const m = new Map<string, number>();
    for (const r of data.rows) {
      const k = String(r[catCol] ?? "Unknown");
      m.set(k, (m.get(k) || 0) + (Number(r[revCol]) || 0));
    }
    const sorted = Array.from(m.entries()).sort((a, b) => b[1] - a[1]);
    return sorted[0]?.[0] ?? null;
  };

  return {
    totalRevenue, totalProfit, growthPct,
    bestRegion: bestBy(regionCol),
    bestProduct: bestBy(productCol),
    revLabel: revCol ?? "Value",
    profLabel: profCol ?? "Profit",
  };
}

function drawHeader(pdf: jsPDF, title: string, page: number, total: number) {
  const pw = pdf.internal.pageSize.getWidth();
  pdf.setFillColor(...NAVY);
  pdf.rect(0, 0, pw, 14, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  pdf.text("COGNILYTIX", 14, 9);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(title, pw / 2, 9, { align: "center" });
  pdf.text(`${page} / ${total}`, pw - 14, 9, { align: "right" });
  pdf.setTextColor(...INK);
}

function drawFooter(pdf: jsPDF) {
  const pw = pdf.internal.pageSize.getWidth();
  const ph = pdf.internal.pageSize.getHeight();
  pdf.setDrawColor(220, 224, 232);
  pdf.line(14, ph - 12, pw - 14, ph - 12);
  pdf.setFontSize(8);
  pdf.setTextColor(...MUTED);
  pdf.text(`Generated by Cognilytix AI · ${new Date().toLocaleDateString()}`, 14, ph - 6);
  pdf.setTextColor(...INK);
}

function wrap(pdf: jsPDF, text: string, x: number, y: number, maxW: number, lh = 5): number {
  const lines = pdf.splitTextToSize(text, maxW);
  pdf.text(lines, x, y);
  return y + lines.length * lh;
}

function sectionTitle(pdf: jsPDF, text: string, y: number): number {
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(15);
  pdf.setTextColor(...NAVY);
  pdf.text(text, 14, y);
  pdf.setDrawColor(...ACCENT);
  pdf.setLineWidth(0.8);
  pdf.line(14, y + 1.5, 40, y + 1.5);
  pdf.setTextColor(...INK);
  pdf.setLineWidth(0.2);
  pdf.setFont("helvetica", "normal");
  return y + 9;
}

function bulletList(pdf: jsPDF, items: string[], y: number, maxW: number): number {
  pdf.setFontSize(10);
  pdf.setTextColor(...INK);
  for (const it of items) {
    pdf.setFillColor(...ACCENT);
    pdf.circle(16, y - 1.5, 0.9, "F");
    y = wrap(pdf, it, 20, y, maxW - 6, 5);
    y += 2;
    if (y > pdf.internal.pageSize.getHeight() - 25) {
      pdf.addPage();
      y = 25;
    }
  }
  return y;
}

export async function generateExecutivePDF(payload: ReportPayload): Promise<Blob> {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = pdf.internal.pageSize.getWidth();
  const ph = pdf.internal.pageSize.getHeight();

  // ---------- COVER ----------
  pdf.setFillColor(...NAVY);
  pdf.rect(0, 0, pw, ph, "F");
  pdf.setFillColor(79, 70, 229);
  pdf.rect(0, ph * 0.55, pw, ph * 0.02, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(36);
  pdf.text(payload.title, pw / 2, ph * 0.4, { align: "center" });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(14);
  pdf.setTextColor(202, 220, 252);
  pdf.text("Executive Business Report", pw / 2, ph * 0.48, { align: "center" });
  pdf.setFontSize(11);
  pdf.text(`Dataset: ${payload.fileName || "—"}`, pw / 2, ph * 0.62, { align: "center" });
  pdf.text(`Generated: ${new Date().toLocaleDateString(undefined, { dateStyle: "long" })}`, pw / 2, ph * 0.66, { align: "center" });
  pdf.setFontSize(9);
  pdf.setTextColor(160, 175, 210);
  pdf.text("Powered by Cognilytix AI", pw / 2, ph - 18, { align: "center" });

  // ---------- KPIs ----------
  pdf.addPage();
  drawHeader(pdf, payload.title, 2, 5);
  let y = sectionTitle(pdf, "Performance Snapshot", 25);

  if (payload.data) {
    const k = computeKPIs(payload.data);
    const cards: { label: string; value: string; accent: [number, number, number] }[] = [
      { label: `Total ${k.revLabel}`, value: fmtNum(k.totalRevenue), accent: [79, 70, 229] },
      { label: `Total ${k.profLabel}`, value: fmtNum(k.totalProfit), accent: [16, 185, 129] },
      { label: "Growth %", value: k.growthPct == null ? "—" : `${k.growthPct.toFixed(1)}%`, accent: [245, 158, 11] },
      { label: "Best Region", value: k.bestRegion ?? "—", accent: [14, 165, 233] },
      { label: "Best Product", value: k.bestProduct ?? "—", accent: [139, 92, 246] },
      { label: "Total Records", value: fmtNum(payload.data.rows.length), accent: [100, 116, 139] },
    ];
    const cardW = (pw - 28 - 12) / 3;
    const cardH = 28;
    cards.forEach((c, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 14 + col * (cardW + 6);
      const cy = y + row * (cardH + 6);
      pdf.setFillColor(248, 250, 252);
      pdf.roundedRect(x, cy, cardW, cardH, 2, 2, "F");
      pdf.setFillColor(...c.accent);
      pdf.roundedRect(x, cy, 1.5, cardH, 1, 1, "F");
      pdf.setFontSize(8);
      pdf.setTextColor(...MUTED);
      pdf.setFont("helvetica", "normal");
      pdf.text(c.label.toUpperCase(), x + 5, cy + 7);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(14);
      pdf.setTextColor(...INK);
      const v = pdf.splitTextToSize(c.value, cardW - 8)[0];
      pdf.text(v, x + 5, cy + 18);
    });
    y += Math.ceil(cards.length / 3) * (cardH + 6) + 6;
  }

  // Executive Summary
  if (payload.executiveSummary) {
    if (y > ph - 50) { pdf.addPage(); drawHeader(pdf, payload.title, 2, 5); y = 25; }
    y = sectionTitle(pdf, "Executive Summary", y + 4);
    pdf.setFontSize(10);
    pdf.setTextColor(...INK);
    y = wrap(pdf, payload.executiveSummary, 14, y, pw - 28, 5);
  }
  drawFooter(pdf);

  // ---------- CHARTS ----------
  const chartEls = document.querySelectorAll("#chart-grid > div, #auto-dashboard-root");
  if (chartEls.length > 0) {
    pdf.addPage();
    drawHeader(pdf, payload.title, 3, 5);
    let cy = sectionTitle(pdf, "Charts & Visualizations", 25);
    const cellW = pw - 28;
    const cellH = 80;
    let i = 0;
    for (const el of Array.from(chartEls)) {
      try {
        const canvas = await html2canvas(el as HTMLElement, { backgroundColor: "#ffffff", scale: 2, useCORS: true, logging: false });
        const img = canvas.toDataURL("image/png");
        const ratio = canvas.width / canvas.height;
        let w = cellW;
        let h = w / ratio;
        if (h > cellH) { h = cellH; w = h * ratio; }
        if (cy + h > ph - 20) {
          pdf.addPage();
          drawHeader(pdf, payload.title, 3, 5);
          cy = 25;
        }
        pdf.addImage(img, "PNG", 14 + (cellW - w) / 2, cy, w, h);
        cy += h + 6;
        i++;
      } catch {
        // skip failed chart
      }
      if (i >= 8) break;
    }
    drawFooter(pdf);
  }

  // ---------- INSIGHTS ----------
  if (payload.insights && payload.insights.length) {
    pdf.addPage();
    drawHeader(pdf, payload.title, 4, 5);
    let iy = sectionTitle(pdf, "AI Insights", 25);
    iy = bulletList(pdf, payload.insights.slice(0, 12), iy, pw - 28);
    if (payload.predictions && payload.predictions.length) {
      iy = sectionTitle(pdf, "Prediction Insights", iy + 4);
      iy = bulletList(pdf, payload.predictions.slice(0, 8), iy, pw - 28);
    }
    drawFooter(pdf);
  }

  // ---------- RECOMMENDATIONS ----------
  if (payload.recommendations && payload.recommendations.length) {
    pdf.addPage();
    drawHeader(pdf, payload.title, 5, 5);
    let ry = sectionTitle(pdf, "Recommendations", 25);
    ry = bulletList(pdf, payload.recommendations.slice(0, 10), ry, pw - 28);
    drawFooter(pdf);
  }

  return pdf.output("blob");
}

export async function downloadExecutivePDF(payload: ReportPayload) {
  const blob = await generateExecutivePDF(payload);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${payload.title.replace(/[^a-z0-9]+/gi, "_")}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}